- .travis.yml
- code/test/main.py
- code/test/test_main.py
Тестовые скрипты и запуск юнит-тестов перенаправлены на директорию "code" 
Добавлены тестовые файлы для сборки хоть какого-то покрытия
> Проверка Pull Request, исправление билда

- .travis.yml
@kirill-kornyakov @AoD314, пожалуйста, позвольте нам увеличить допустимое число символов в строке с 79 до 120.
> Увеличение числа символов в строке до 110

- code/fraction/model/test_pavel_baranov.py
> Баранов - Лабораторная работа #0

- code/fraction/model/test_AntonGrishin.py
@homksei
@sawirani
@mariamosonova
> Гришин - Лабораторная работа #0

- code/fraction/model/test_Anastasiia_Grishina.py
@antongrishin
@homksei
@GerasimovDG
> Гришина - Лабораторная работа #0

- code/color_space/view/view.py
- code/fraction/cliview/cli_view.py
- code/fraction/guiview/gui_view.py
- code/fraction/model/test_fraction_kapkaev.py
- code/matrix/gui_view/gui_view.py
@VikaSannikova @AntonGrishin @ZinovievVladimir
> Капкаев - Лабораторная работа #0

- code/color_space/view/view.py
- code/fraction/cliview/cli_view.py
- code/fraction/guiview/gui_view.py
- code/fraction/model/test_fraction_sannikova.py
- code/matrix/gui_view/gui_view.py
Накидайте лайков/замечаний 
@pavelbar @ZinovievVladimir @kapkaevn
> Санникова - Лабораторная работа #0

- code/fraction/model/test_KuznetsovVladislav.py
> Кузнецов Владислав - Лабораторная работа #0

- code/fraction/model/test_samarkina.py
> Самаркина - Лабораторная работа #0

- code/fraction/model/test_anastasia_senina.py
@JuliaKamelina @UsovaMA please review
> Сенина - Лабораторная работа #0

- code/fraction/model/test_konakov_aleksandr.py
@vzinovie @RodionovF  @AleksandrPanov
> Конаков - Лабораторная работа #0

- code/fraction/model/test_roman_daniil.py
> Роман - Лабораторная работа #0 

- code/fraction/model/test_usova_marina.py
@AnastasiaaSenina @JuliaKamelina please review
> Усова Марина - Лабораторная работа #0

- code/fraction/model/test_okunev_boris.py
> Окунев - Лабораторная работа #0

- code/fraction/model/test_kamelina_julia.py
@AnastasiaaSenina @UsovaMA please review
> Камелина - Лабораторная работа #0

- code/fraction/model/test_krasikova_ekaterina.py
> Красикова - Лабораторная работа #0

- code/krasikova_ekaterina_lab1/model/dheap.py
- code/krasikova_ekaterina_lab1/model/test_dheap.py
> Красикова - Лабораторная работа #1

- code/grishina_anastasiia/arab_roman_converter/arab_roman_converter.py
- code/grishina_anastasiia/arab_roman_converter/test_arab_roman_converter.py
- code/grishina_anastasiia/arab_to_roman_converter/arab_to_roman_converter.py
- code/grishina_anastasiia/arab_to_roman_converter/test_arab_to_roman_converter.py
> Гришинa - Лабораторная работа #1

- code/fraction/model/test_senyaev_andrey.py
@kkonsw @GorozhaninMihail @AleksandrGeneralov @SemenDoc @AntonGrishin please, review
> Сеняев - Лабораторная работа #0

- code/big_integer/logger/fakelogger.py
- code/big_integer/logger/ilogger.py
- code/big_integer/logger/reallogger.py
- code/big_integer/logger/test_fakelogger.py
- code/big_integer/viewmodel/viewmodel.py
- code/big_integer/viewmodel/viewmodel_test.py
> Ванеев - Лабораторная работа #3

- code/string_calculator/logger/fakelogger.py
- code/string_calculator/logger/ilogger.py
- code/string_calculator/logger/reallogger.py
- code/string_calculator/logger/test_fakelogger.py
- code/string_calculator/viewmodel/tests_for_viewmodel.py
- code/string_calculator/viewmodel/viewmodel.py
> Глуздов - Лабораторная работа #3

- code/fibonacci_heap/logger/fakelogger.py
- code/fibonacci_heap/logger/ilogger.py
- code/fibonacci_heap/logger/reallogger.py
- code/fibonacci_heap/logger/test_fakelogger.py
- code/fibonacci_heap/viewmodel/main_viewmodel.py
- code/fibonacci_heap/viewmodel/test_main_viewmodel.py
add logging for Fibonacci heap model
> Протас Мария - Лабораторная работа #3

- code/debt_expenses/logger/fake_logger.py
- code/debt_expenses/logger/ilogger.py
- code/debt_expenses/logger/real_logger.py
- code/debt_expenses/unittests/logger_unittests.py
- code/debt_expenses/view/debt_view.py
- code/debt_expenses/viewmodel/debt_viewmodel.py
@Fulmo @vzinovie please review ^^
> Кузнецов Виктор - Лабораторная работа #3

- code/priority_queue/logger/fakelogger.py
- code/priority_queue/logger/ilogger.py
- code/priority_queue/logger/reallogger.py
- code/priority_queue/logger/test_fakeflogger.py
- code/priority_queue/viewmodel/pq_viewmodel.py
- code/priority_queue/viewmodel/test_pq_viewmodel.py
> Конаков - Лабораторная работа #3
